onto: "../ontology.txt"
train: "../labels.csv"
label_col: "ami"
mutations: "../genotype_data.h5"
epoch: 5
lr: 0.0001
wd: 0.001
alpha: 0.3
batchsize: 256
modeldir: "/model_test/"
cuda: 0
gene2id: "../ukb_snp_ids.csv"
genotype_hiddens: 4
optimize: 1
zscore_method: "auc"
std: "/model_test/std.txt"
patience: 30
delta: 0.001
min_dropout_layer: 10
dropout_fraction: 0.25
lr_step_size: 3
activation: "leaky_relu"
task: "classification"
onehot: True
num_workers: 8
run_name: "ami"
num_covariates: 2